// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6kjHWDhKubVaw5yDJdabotST6m8pc2LE',
    appId: '1:309122456853:web:eebee1a1c978f8f687dd1c',
    messagingSenderId: '309122456853',
    projectId: 'quran-app-499be',
    authDomain: 'quran-app-499be.firebaseapp.com',
    storageBucket: 'quran-app-499be.appspot.com',
    measurementId: 'G-7PJEF5PLM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJuX6MCi3-IsU_Plkg7z182QlqqrL5e7M',
    appId: '1:309122456853:android:51ed150020cf12eb87dd1c',
    messagingSenderId: '309122456853',
    projectId: 'quran-app-499be',
    storageBucket: 'quran-app-499be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn7Bd_Jhe7lJj9CJJHmK6oLrOIjbXNQ3A',
    appId: '1:309122456853:ios:118dd902ccccd80187dd1c',
    messagingSenderId: '309122456853',
    projectId: 'quran-app-499be',
    storageBucket: 'quran-app-499be.appspot.com',
    iosBundleId: 'com.example.quran',
  );
}
